"""Thread report — self-contained HTML report generator.

Single HTML file with inline Chart.js from CDN. Three headline numbers,
two line charts (fidelity and effort over time), and a workflow-aware
details table: top epics for epic/mixed workflows, a project summary
for flat workflows.
"""

import json
from pathlib import Path

import duckdb


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Thread report</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif;
         max-width: 1100px; margin: 2rem auto; padding: 0 1rem;
         color: #222; line-height: 1.5; }}
  h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.3em; }}
  .workflow-tag {{ display: inline-block; padding: 0.25rem 0.6rem;
                   background: #eef; border-radius: 4px; font-size: 0.85rem;
                   color: #335; margin-left: 0.5rem; }}
  .headline {{ display: flex; gap: 2rem; margin: 2rem 0; }}
  .headline .stat {{ flex: 1; padding: 1.5rem; background: #f6f6f6;
                     border-radius: 8px; text-align: center; }}
  .headline .value {{ font-size: 2.5rem; font-weight: bold; }}
  .headline .label {{ color: #666; font-size: 0.9rem; text-transform: uppercase; }}
  .chart-container {{ margin: 2rem 0; }}
  canvas {{ max-width: 100%; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th, td {{ padding: 0.5rem; text-align: left; border-bottom: 1px solid #ddd; }}
  th {{ background: #f6f6f6; }}
  .footer {{ color: #888; font-size: 0.85rem; margin-top: 3rem; }}
</style>
</head>
<body>
<h1>Thread report <span class="workflow-tag">{workflow_type}</span></h1>
<p>Forensics and patterns from your Beads history. {shape_summary}</p>

<div class="headline">
  <div class="stat">
    <div class="value">{fidelity}</div>
    <div class="label">Fidelity score</div>
  </div>
  <div class="stat">
    <div class="value">{effort}</div>
    <div class="label">Rework cost (avg)</div>
  </div>
  <div class="stat">
    <div class="value">{closed}</div>
    <div class="label">Beads closed</div>
  </div>
</div>

<div class="chart-container">
  <h2>Fidelity over time</h2>
  <canvas id="fidelityChart"></canvas>
</div>

<div class="chart-container">
  <h2>Rework cost over time</h2>
  <canvas id="effortChart"></canvas>
</div>

{details_section}

<p class="footer">Generated by Thread. Data source: thread.duckdb.</p>

<script>
const weeklyData = {weekly_json};

new Chart(document.getElementById('fidelityChart'), {{
  type: 'line',
  data: {{
    labels: weeklyData.map(d => d.week),
    datasets: [{{
      label: 'Avg fidelity',
      data: weeklyData.map(d => d.avg_fidelity),
      borderColor: '#2a7',
      tension: 0.2,
    }}]
  }},
  options: {{ scales: {{ y: {{ min: 0, max: 1 }} }} }}
}});

new Chart(document.getElementById('effortChart'), {{
  type: 'line',
  data: {{
    labels: weeklyData.map(d => d.week),
    datasets: [{{
      label: 'Avg rework cost',
      data: weeklyData.map(d => d.avg_effort),
      borderColor: '#a27',
      tension: 0.2,
    }}]
  }}
}});
</script>
</body>
</html>
"""


def _fmt(val, precision=2):
    if val is None:
        return "—"
    if isinstance(val, bool):
        return str(val)
    if isinstance(val, int):
        return str(val)
    try:
        return f"{float(val):.{precision}f}"
    except (TypeError, ValueError):
        return str(val)


def _fmt_epic_row(row: dict) -> str:
    return (
        "    <tr>"
        f"<td>{row.get('epic_title') or '—'}</td>"
        f"<td>{row.get('bead_count') or 0}</td>"
        f"<td>{_fmt(row.get('avg_fidelity_score'))}</td>"
        f"<td>{_fmt(row.get('avg_effort_score'))}</td>"
        f"<td>{_fmt(row.get('total_effort_penalty'))}</td>"
        f"<td>{_fmt(row.get('elapsed_vs_estimate_ratio'))}</td>"
        f"<td>{row.get('epic_had_criteria') if row.get('epic_had_criteria') is not None else '—'}</td>"
        f"<td>{row.get('total_compactions') or 0}</td>"
        "</tr>"
    )


def _epic_details_section(epic_dicts: list) -> str:
    rows_html = "\n".join(_fmt_epic_row(e) for e in epic_dicts) or \
        "    <tr><td colspan='8'>No epics found.</td></tr>"
    return (
        "<h2>Top epics by effort penalty</h2>\n"
        "<table>\n"
        "  <thead>\n"
        "    <tr>\n"
        "      <th>Epic</th>\n"
        "      <th>Beads</th>\n"
        "      <th>Fidelity</th>\n"
        "      <th>Rework</th>\n"
        "      <th>Penalty</th>\n"
        "      <th>Elapsed vs estimate</th>\n"
        "      <th>Had criteria</th>\n"
        "      <th>Compactions</th>\n"
        "    </tr>\n"
        "  </thead>\n"
        "  <tbody>\n"
        f"{rows_html}\n"
        "  </tbody>\n"
        "</table>"
    )


def _project_details_section(proj: dict) -> str:
    return (
        "<h2>Project summary</h2>\n"
        "<table>\n"
        "  <tbody>\n"
        f"    <tr><th>Total beads</th><td>{proj.get('total_beads') or 0}</td></tr>\n"
        f"    <tr><th>Singleton beads</th><td>{proj.get('singleton_bead_count') or 0}</td></tr>\n"
        f"    <tr><th>Epics</th><td>{proj.get('epic_count') or 0}</td></tr>\n"
        f"    <tr><th>Avg fidelity</th><td>{_fmt(proj.get('avg_fidelity_score'))}</td></tr>\n"
        f"    <tr><th>Avg rework cost</th><td>{_fmt(proj.get('avg_effort_score'))}</td></tr>\n"
        f"    <tr><th>Total reopens</th><td>{proj.get('total_reopens') or 0}</td></tr>\n"
        f"    <tr><th>Total compactions</th><td>{proj.get('total_compactions') or 0}</td></tr>\n"
        f"    <tr><th>Agent closure rate</th><td>{_fmt(proj.get('agent_closure_rate'))}</td></tr>\n"
        "  </tbody>\n"
        "</table>"
    )


def _detect_workflow_type(epic_count: int, singleton_count: int) -> str:
    if epic_count > 0 and singleton_count == 0:
        return "epic"
    if epic_count == 0 and singleton_count > 0:
        return "flat"
    if epic_count == 0 and singleton_count == 0:
        return "empty"
    return "mixed"


def generate_report(db_path: str, output_path: str) -> str:
    """Generate thread-report.html at output_path. Returns the path."""
    conn = duckdb.connect(db_path, read_only=True)
    try:
        # Project-level shape + headline metrics
        proj_row = conn.execute(
            "SELECT total_beads, singleton_bead_count, epic_count, "
            "  avg_fidelity_score, avg_effort_score, total_reopens, "
            "  total_compactions, agent_closure_rate "
            "FROM mart_project_summary"
        ).fetchone()
        proj = {
            "total_beads": proj_row[0] if proj_row else 0,
            "singleton_bead_count": proj_row[1] if proj_row else 0,
            "epic_count": proj_row[2] if proj_row else 0,
            "avg_fidelity_score": proj_row[3] if proj_row else None,
            "avg_effort_score": proj_row[4] if proj_row else None,
            "total_reopens": proj_row[5] if proj_row else 0,
            "total_compactions": proj_row[6] if proj_row else 0,
            "agent_closure_rate": proj_row[7] if proj_row else None,
        }
        workflow_type = _detect_workflow_type(
            proj["epic_count"] or 0, proj["singleton_bead_count"] or 0
        )

        # Closed-bead count for the headline card
        closed_row = conn.execute(
            "SELECT COUNT(*) FROM fact_bead_lifecycle "
            "WHERE final_closed_at IS NOT NULL"
        ).fetchone()
        closed = closed_row[0] if closed_row else 0

        # Weekly trends for the charts (always shown)
        weekly_rows = conn.execute(
            "SELECT week, avg_fidelity, avg_effort FROM v_weekly_trends "
            "ORDER BY week"
        ).fetchall()
        weekly_data = [
            {
                "week": str(r[0])[:10] if r[0] else None,
                "avg_fidelity": float(r[1]) if r[1] is not None else None,
                "avg_effort": float(r[2]) if r[2] is not None else None,
            }
            for r in weekly_rows
        ]

        # Details section varies by workflow type
        if workflow_type in ("epic", "mixed"):
            epic_rows = conn.execute(
                "SELECT epic_title, bead_count, avg_fidelity_score, "
                "  avg_effort_score, total_effort_penalty, total_compactions, "
                "  epic_had_criteria, elapsed_vs_estimate_ratio "
                "FROM mart_epic_summary "
                "WHERE epic_is_template = false OR epic_is_template IS NULL "
                "ORDER BY COALESCE(total_effort_penalty, 0) DESC, "
                "  COALESCE(avg_fidelity_score, 1) ASC "
                "LIMIT 10"
            ).fetchall()
            epic_dicts = [
                {
                    "epic_title": r[0],
                    "bead_count": r[1],
                    "avg_fidelity_score": r[2],
                    "avg_effort_score": r[3],
                    "total_effort_penalty": r[4],
                    "total_compactions": r[5],
                    "epic_had_criteria": r[6],
                    "elapsed_vs_estimate_ratio": r[7],
                }
                for r in epic_rows
            ]
            details_section = _epic_details_section(epic_dicts)
        else:
            details_section = _project_details_section(proj)

    finally:
        conn.close()

    shape_summary = (
        f"{proj['total_beads']} beads · "
        f"{proj['epic_count']} epics · "
        f"{proj['singleton_bead_count']} singletons"
    )

    html = HTML_TEMPLATE.format(
        workflow_type=workflow_type,
        shape_summary=shape_summary,
        fidelity=_fmt(proj["avg_fidelity_score"]),
        effort=_fmt(proj["avg_effort_score"]),
        closed=closed,
        weekly_json=json.dumps(weekly_data),
        details_section=details_section,
    )

    out = Path(output_path)
    out.write_text(html)
    return str(out)
